version: 2
jobs:
  build:
    branches:
      only: master
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    steps:
      - checkout
      - run:
          name: Git config
          command: |
            git config --global user.email "noreply@example.com"
            git config --global user.name "CircleCI Bot"
      - run:
          name: Git submodule
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Git worktree
          command: |
             git worktree add -B gh-pages src/site/public origin/gh-pages
      - run:
          name: Hugo build
          command: |
            hugo -v -s src/site
      - add_ssh_keys:
          fingerprints:
            - "b9:0e:6b:5e:fe:2f:aa:b2:f6:05:25:97:8f:33:93:94"
      - deploy:
          command: |
            cd src/site/public
            git add --all
            git commit --allow-empty -m "Automated publish to gh-pages [ci skip]"
            git push
