baseURL = "./"
languageCode = "en-us"
title = "ServerlessDays Fukuoka"
canonifyurls = true

[params]
    logo = "/images/logo_fukuoka.png"
    description = "A community based conference focusing on Serverless based platforms and technologies. Fukuoka, October, 2019"
    mascot = "/images/Anteater_mascot.png"
    date = "December 14, 2019"
    city = "Fukuoka"
    twitter = "serverlessjp"
    email = "japan@serverlessdays.io"
    backgroundImage = "/serverlessdays-fukuoka/images/fukuoka_blue.jpg"
    backgroundImageAuthor = "Photo by Moyan Brenn"
    backgroundImageCopyRight = "CC BY"
    thumbnailImage = "/images/fukuoka-thumbnail-min.jpg"
    ccLink = "https://creativecommons.org/licenses/by/2.0/"
    prospectus = "https://www.dropbox.com/s/b1rdbmc14fv7lta/ServerlessDaysJapanTour2019_Overview4Sponsors.2019.6.pdf"
    ticketDate = "early September, 2019"
    ticketDate_ja = "2019年9月上旬"
    ticketSaleUrl = "https://serverlessdays-fukuoka-2019.eventbrite.com"
    cfpDate = "early August, 2019"
    cfpDate_ja = "2019年8月上旬"
    cfpEndDate = "early November, 2019"
    cfpEndDate_ja = "2019年11月上旬"
    cfpUrl = "https://www.papercall.io/slsdaysfukuoka2019"
    emailForm = "https://forms.gle/xCB8wPj48hEf8t8E7"

[[params.dates]]
    date = "early August, 2019"
    text = "CFP Opens"
    done = true

[[params.dates]]
    date = "early September, 2019"
    text = "Tickets go on sale"
    done = false

[[params.dates]]
    date = "early November, 2019"
    text = "CFP closes"
    done = false

[[params.dates]]
    date = "Late November, 2019"
    text = "Speakers announced"
    done = false

[[params.dates]]
    date = "December 13, 2019"
    text = "Serverless Workshops"
    done = false

[[params.dates]]
    date = "December 14, 2019"
    text = "Serverless Days Fukuoka"
    done = false

[[params.dates_ja]]
    date = "2019年8月上旬"
    text = "CFP募集開始"
    done = true

[[params.dates_ja]]
    date = "2019年9月上旬"
    text = "チケット販売開始"
    done = false

[[params.dates_ja]]
    date = "2019年11月上旬"
    text = "CFP募集締切"
    done = false

[[params.dates_ja]]
    date = "2019年11月下旬"
    text = "スピーカー発表"
    done = false

[[params.dates_ja]]
    date = "2019年12月13日"
    text = "ServerlessDays Fukuokaワークショップ@天神駅周辺"
    done = false

[[params.dates_ja]]
    date = "2019年12月14日"
    text = "ServerlessDays Fukuokaカンファレンスデイ@LINE Fukuoka"
    done = false

[params.venue]
    name = "LINE Fukuoka株式会社"
    link = "https://linefukuoka.co.jp/ja/"
    map = "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d13294.62732071876!2d130.4190616!3d33.5882583!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x8dd36b398d44a197!2zTElORSBGdWt1b2th5qCq5byP5Lya56S-!5e0!3m2!1sja!2s jp!4v1563257449637!5m2!1sja!2sjp"
    text = "JRJP Hakata Bldg. 12F, 8-1 Hakataekichuogai, Hakata Ward, Fukuoka, Fukuoka Prefecture 812-0012"
    text_ja = "〒812-0012 福岡県福岡市博多区博多駅中央街8-1 JRJP博多ビル12F"
